### ISSUE TITLE
Empty Browser

### ISSUE THREAD

**Issue by ghost** [projectyang/poker-room#5]
After installing:
"npm install"
and "npm start"
I try to load "localhost:3000" but just get an empty website.
The server registred my connection.
and in terminal is written: 
C:\Users\Julian\Desktop\poker-room-master>npm start

 simple-react@1.0.0 start C:\Users\Julian\Desktop\poker-room-master
 node server/app.js

Listening on port 3000
GET / 304 7.996 ms - -
GET /bundle.js 304 3.553 ms - -

screenshot https://prnt.sc/o1s6ae
It would be great if you can tell me how to fix this.

**Comment by projectyang** [comment]
Hey @StahlBetong, sorry for the late reply. 

This seems to have been an issue with some outdated node modules. I've made a quick fix. It should be good now - please run npm install and try starting it again. :)
