### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by TommyB1992** [projectyang/poker-room#7]
Hello Sir,
I have this trouble, how can i resolve it?

```
ERROR in ./client/index.js
Module not found: Error: Can't resolve './game' in '/home/tomas/Desktop/poker-room-master/client'
 @ ./client/index.js 15:12-29

```

p.s. I don't have the folder '/game/'

**Comment by projectyang** [comment]
Hi @TommyB1992,

You wouldn't need a /game folder, it's referring to the Game.js. This is weird - I just tested the repo myself and it seems to have worked fine. Have you made any modifications?

**Comment by TommyB1992** [comment]
> Hi @TommyB1992,
> 
> You wouldn't need a /game folder, it's referring to the Game.js. This is weird - I just tested the repo myself and it seems to have worked fine. Have you made any modifications?

No Sir, I didn't make any modification.

Thank you

**Comment by projectyang** [comment]
Hmmm, just as a quick check, can you try cloning it again and running npm install?

**Comment by TommyB1992** [comment]
I tried, but nothing to do.

**Comment by projectyang** [comment]
Can you send over your package.json?

**Comment by TommyB1992** [comment]
Of course :)
```

{
  "name": "simple-react",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack -w & nodemon server/app.js --ignore public",
    "test": "echo \"Error: no test specified\" && exit 1",
    "deploy": "sh ./scripts/deploy.sh"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@livechat/ui-kit": "^0.1.0",
    "@material-ui/core": "^1.2.0",
    "@tmkelly28/tk-css": "^1.0.2",
    "axios": "^0.18.0",
    "body-parser": "^1.18.2",
    "express": "^4.16.3",
    "handranker": "^1.0.5",
    "moment": "^2.22.2",
    "morgan": "^1.9.0",
    "normalizr": "^3.2.4",
    "pg": "^7.4.1",
    "pg-hstore": "^2.3.2",
    "react": "^16.8.6",
    "react-dom": "^16.2.0",
    "react-infinite": "^0.13.0",
    "react-rangeslider": "^2.2.0",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.2.2",
    "react-sound": "^1.2.0",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "reselect": "^3.0.1",
    "socket.io": "^2.1.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.3",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "css-loader": "^3.0.0",
    "nodemon": "^1.17.2",
    "style-loader": "^0.20.2",
    "webpack": "^4.34.0",
    "webpack-cli": "^3.3.4",
    "webpack-dev-server": "^3.1.0"
  }
}

```

**Comment by projectyang** [comment]
Ok cool. Can you also confirm all the files are present in your client folder? Should be something like this:

![Screen Shot 2019-07-19 at 11 21 18 AM](https://user-images.githubusercontent.com/13473834/61546339-63fcea80-aa17-11e9-8c8f-997b5f448d56.png)

**Comment by TommyB1992** [comment]
I confirm it.
https://i.imgur.com/KZ5y3Km.png

**Comment by projectyang** [comment]
I'm not exactly sure why it's not working. 

Looking at your webpack log - it seems much different from mine, mainly the bundle.js sizing and also the number of node_modules. Was there any issues when you did npm install? Here's my output:

> ➜  poker-room git:(master) npm i
npm WARN enzyme-adapter-react-16@1.1.1 requires a peer of enzyme@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN recompose@0.23.5 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN simple-react@1.0.0 No repository field.
audited 14839 packages in 6.222s
found 0 vulnerabilities

I also noticed your folder is poker-room-master, did you specifically clone it into a different folder name for a reason?

**Comment by projectyang** [comment]
Are you on linux by any chance?

**Comment by TommyB1992** [comment]
> Was there any issues when you did npm install? Here's my output:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

> I also noticed your folder is poker-room-master, did you specifically clone it into a different folder name for a reason?

poker-room-master is the original name of .zip archive.

> Are you on linux by any chance? I think it might be related to this issue if so:

Yes Sir I'm on Linux. How can I find what names I have to replace?

**Comment by projectyang** [comment]
> > Are you on linux by any chance? I think it might be related to this issue if so:
> 
> Yes Sir I'm on Linux. How can I find what names have I to replace?

You can try replacing the paths from ./game to ./Game and see if that helps - I suspect that's why webpack is having trouble finding the missing modules. 

Sorry, but I can't really help much here.

**Comment by TommyB1992** [comment]
> Sorry, but I can't really help much here.
Isn't request! Now it works!!!

Thank you very much!
